import 'package:flutter_test/flutter_test.dart';
import 'package:aqua_rythu/systems/feed_intelligence_engine.dart';
import 'models/farm_scenario.dart';
import 'utils/scenario_runner.dart';

const scenarios = <FarmScenario>[
  FarmScenario(
    name: 'Clean system',
    trayFactor: 1.0,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Maintain Feeding',
  ),
  FarmScenario(
    name: 'Overfeeding yesterday',
    trayFactor: 1.0,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.overfeeding,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Reduce Feeding',
  ),
  FarmScenario(
    name: 'Underfeeding yesterday',
    trayFactor: 1.0,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.underfeeding,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Increase Feeding',
  ),
  FarmScenario(
    name: 'High tray leftover',
    trayFactor: 0.80,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Reduce Feeding',
  ),
  FarmScenario(
    name: 'Tray empty',
    trayFactor: 1.10,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Increase Feeding',
  ),
  FarmScenario(
    name: 'Tray neutral noise',
    trayFactor: 1.02,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Maintain Feeding',
  ),
  FarmScenario(
    name: 'Growth below expected',
    trayFactor: 1.0,
    growthFactor: 0.90,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Reduce Feeding',
  ),
  FarmScenario(
    name: 'Growth above expected',
    trayFactor: 1.0,
    growthFactor: 1.10,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Increase Feeding',
  ),
  FarmScenario(
    name: 'Growth neutral noise',
    trayFactor: 1.0,
    growthFactor: 1.02,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Maintain Feeding',
  ),
  FarmScenario(
    name: 'Mild environment stress',
    trayFactor: 1.0,
    growthFactor: 1.0,
    environmentFactor: 0.90,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Reduce Feeding',
  ),
  FarmScenario(
    name: 'Critical stop due to water',
    trayFactor: 1.10,
    growthFactor: 1.10,
    environmentFactor: 0.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: true,
    expectedAction: 'Stop Feeding',
  ),
  FarmScenario(
    name: 'Bad FCR only',
    trayFactor: 1.0,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 0.85,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Reduce Feeding',
  ),
  FarmScenario(
    name: 'Good FCR does not force increase',
    trayFactor: 1.0,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 1.10,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Maintain Feeding',
  ),
  FarmScenario(
    name: 'Tray empty with overfeeding yesterday',
    trayFactor: 1.10,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.overfeeding,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Reduce Feeding',
  ),
  FarmScenario(
    name: 'Tray leftover with growth high',
    trayFactor: 0.80,
    growthFactor: 1.10,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Reduce Feeding',
  ),
  FarmScenario(
    name: 'Tray leftover with underfeeding',
    trayFactor: 0.80,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.underfeeding,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Reduce Feeding',
  ),
  FarmScenario(
    name: 'No actual data ignores intelligence',
    trayFactor: 1.0,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.overfeeding,
    hasActualData: false,
    isCriticalStop: false,
    expectedAction: 'Maintain Feeding',
  ),
  FarmScenario(
    name: 'Small tray variation noisy',
    trayFactor: 0.97,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Maintain Feeding',
  ),
  FarmScenario(
    name: 'Small growth variation noisy',
    trayFactor: 1.0,
    growthFactor: 1.03,
    environmentFactor: 1.0,
    fcrFactor: 1.0,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Maintain Feeding',
  ),
  FarmScenario(
    name: 'Tray empty with bad FCR',
    trayFactor: 1.10,
    growthFactor: 1.0,
    environmentFactor: 1.0,
    fcrFactor: 0.85,
    intelligenceStatus: FeedStatus.onTrack,
    hasActualData: true,
    isCriticalStop: false,
    expectedAction: 'Increase Feeding',
  ),
];

void main() {
  group('Feed Decision Simulation', () {
    for (final scenario in scenarios) {
      test(scenario.name, () {
        final result = runScenario(scenario);

        if (result.action != scenario.expectedAction) {
          print('❌ Scenario Failed: ${scenario.name}');
          print('Expected: ${scenario.expectedAction}');
          print('Got: ${result.action}');
          print('Reason: ${result.reason}');
          print('Trace: ${result.decisionTrace}');
        }

        expect(
          result.action,
          scenario.expectedAction,
          reason: 'Failed scenario: ${scenario.name}',
        );
      });
    }
  });
}
