import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { upsertSubscription } from '../_shared/upsert_subscription.ts'
import { logPayment } from '../_shared/payment_logger.ts'
import { logAudit } from '../_shared/audit_logger.ts'

const RAZORPAY_KEY_ID        = Deno.env.get('RAZORPAY_KEY_ID')!
const RAZORPAY_KEY_SECRET    = Deno.env.get('RAZORPAY_KEY_SECRET')!
const SUPABASE_URL           = Deno.env.get('SUPABASE_URL')!
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  })

async function hmacSha256(secret: string, message: string): Promise<string> {
  const enc = new TextEncoder()
  const key = await crypto.subtle.importKey(
    'raw', enc.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false, ['sign'],
  )
  const sig = await crypto.subtle.sign('HMAC', key, enc.encode(message))
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, '0')).join('')
}

serve(async (req) => {
  if (req.method !== 'POST') return new Response('Method not allowed', { status: 405 })

  // ── Auth ──────────────────────────────────────────────────────────────────
  const authHeader = req.headers.get('Authorization')
  if (!authHeader?.startsWith('Bearer ')) return new Response('Unauthorized', { status: 401 })

  // ── Input validation ──────────────────────────────────────────────────────
  let body: { payment_id: string; order_id: string; signature: string; plan_type: string; price: number }
  try { body = await req.json() } catch { return json({ error: 'Invalid JSON' }, 400) }

  const { payment_id, order_id, signature, plan_type, price } = body
  if (!payment_id || !order_id || !signature || !plan_type || price == null) {
    return json({ error: 'Missing required fields' }, 400)
  }

  // ── Phase 1: HMAC signature verification — before any DB or API work ──────
  // Verifies the payment proof was generated by Razorpay, not forged by the client.
  const expected = await hmacSha256(RAZORPAY_KEY_SECRET, `${order_id}|${payment_id}`)
  if (expected !== signature) {
    // Authenticate user for audit log only — don't leak which field failed
    const supabaseForAudit = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)
    await logAudit(supabaseForAudit, {
      eventType: 'signature_mismatch',
      paymentId: payment_id,
      orderId:   order_id,
      severity:  'critical',
      details:   { reason: 'hmac_mismatch' },
    })
    return json({ error: 'Payment signature mismatch — request rejected' }, 400)
  }

  // ── Authenticate user ─────────────────────────────────────────────────────
  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)
  const { data: { user }, error: authError } = await supabase.auth.getUser(
    authHeader.slice('Bearer '.length),
  )
  if (authError || !user) return new Response('Unauthorized', { status: 401 })

  // ── Phase 1: Cross-check amount vs payment_orders ─────────────────────────
  // Prevents amount tampering: the order was created server-side, so its
  // amount is authoritative. Client-submitted price must match exactly.
  const { data: orderRow, error: orderError } = await supabase
    .from('payment_orders')
    .select('amount, plan_type')
    .eq('order_id', order_id)
    .maybeSingle()

  if (orderError || !orderRow) {
    return json({ error: 'Order not found. Please retry.' }, 404)
  }

  const priceInPaise = Math.round(price * 100)
  if (orderRow.amount !== priceInPaise) {
    await Promise.all([
      logPayment(supabase, {
        userId: user.id, orderId: order_id, paymentId: payment_id,
        status: 'failed', source: 'client',
        errorMessage: `amount_mismatch: expected ${orderRow.amount}, got ${priceInPaise}`,
      }),
      logAudit(supabase, {
        eventType: 'amount_mismatch',
        userId:    user.id,
        paymentId: payment_id,
        orderId:   order_id,
        severity:  'critical',
        details:   { expected_paise: orderRow.amount, submitted_paise: priceInPaise },
      }),
    ])
    return json({ error: 'Payment amount mismatch — request rejected.' }, 400)
  }

  // ── Phase 1: Razorpay API verification — confirm payment actually captured ─
  // HMAC proves Razorpay signed the response but does not confirm the payment
  // status hasn't changed (e.g. refunded, failed after signing). We call the
  // Razorpay API to assert status = 'captured' before activating any entitlement.
  const rzpCredentials = btoa(`${RAZORPAY_KEY_ID}:${RAZORPAY_KEY_SECRET}`)
  let rzpPayment: { status: string; order_id: string; amount: number }

  try {
    const rzpResponse = await fetch(`https://api.razorpay.com/v1/payments/${payment_id}`, {
      headers: { Authorization: `Basic ${rzpCredentials}` },
    })

    if (!rzpResponse.ok) {
      await logAudit(supabase, {
        eventType: 'razorpay_api_error',
        userId:    user.id,
        paymentId: payment_id,
        orderId:   order_id,
        severity:  'warn',
        details:   { http_status: rzpResponse.status },
      })
      // 503 so the client can retry — HMAC is valid, payment is likely real
      return json({ error: 'Payment verification unavailable. Please retry.', code: 'RZP_API_UNAVAILABLE' }, 503)
    }

    rzpPayment = await rzpResponse.json()
  } catch (networkErr) {
    await logAudit(supabase, {
      eventType: 'razorpay_api_error',
      userId:    user.id,
      paymentId: payment_id,
      orderId:   order_id,
      severity:  'warn',
      details:   { reason: 'network_error', error: String(networkErr) },
    })
    return json({ error: 'Payment verification unavailable. Please retry.', code: 'RZP_API_UNAVAILABLE' }, 503)
  }

  // Confirm payment is captured (not just initiated or refunded)
  if (rzpPayment.status !== 'captured') {
    await logAudit(supabase, {
      eventType: 'payment_not_captured',
      userId:    user.id,
      paymentId: payment_id,
      orderId:   order_id,
      severity:  'critical',
      details:   { razorpay_status: rzpPayment.status },
    })
    return json({ error: 'Payment not captured — activation rejected.' }, 400)
  }

  // Confirm Razorpay's order_id matches what the client sent (prevents order substitution)
  if (rzpPayment.order_id !== order_id) {
    await logAudit(supabase, {
      eventType: 'signature_mismatch',
      userId:    user.id,
      paymentId: payment_id,
      orderId:   order_id,
      severity:  'critical',
      details:   { claimed_order_id: order_id, actual_order_id: rzpPayment.order_id },
    })
    return json({ error: 'Order ID mismatch — request rejected.' }, 400)
  }

  // ── Phase 7: Persist payment proof before subscription creation ───────────
  await supabase.from('pending_payments').upsert(
    {
      user_id:    user.id,
      order_id,
      payment_id,
      signature,
      plan_type:  plan_type.toLowerCase(),
      price,
      status:     'pending',
      created_at: new Date().toISOString(),
    },
    { onConflict: 'payment_id', ignoreDuplicates: true },
  )

  // ── Phase 3: Idempotent subscription creation (replay-safe) ──────────────
  // upsertSubscription checks UNIQUE(payment_id) — duplicate calls return the
  // existing row instead of creating a second subscription.
  try {
    const { subscription, alreadyExisted } = await upsertSubscription(supabase, {
      paymentId: payment_id,
      orderId:   order_id,
      userId:    user.id,
      planType:  plan_type,
      price,
    })

    await Promise.all([
      logPayment(supabase, {
        userId: user.id, orderId: order_id, paymentId: payment_id,
        status: 'success', source: 'client',
        errorMessage: alreadyExisted ? 'already_existed' : undefined,
      }),
      logAudit(supabase, {
        eventType: alreadyExisted ? 'duplicate_verification' : 'subscription_activated',
        userId:    user.id,
        paymentId: payment_id,
        orderId:   order_id,
        severity:  alreadyExisted ? 'warn' : 'info',
        details:   { plan_type, already_existed: alreadyExisted },
      }),
    ])

    return json(subscription)
  } catch (err) {
    await Promise.all([
      logPayment(supabase, {
        userId: user.id, orderId: order_id, paymentId: payment_id,
        status: 'failed', source: 'client',
        errorMessage: String(err),
      }),
      logAudit(supabase, {
        eventType: 'subscription_activated',
        userId:    user.id,
        paymentId: payment_id,
        orderId:   order_id,
        severity:  'critical',
        details:   { error: String(err), stage: 'db_write' },
      }),
    ])

    return json(
      { error: 'Subscription creation failed. Payment is safe — please retry.', code: 'DB_WRITE_FAILED' },
      503,
    )
  }
})
