-- =============================================================
-- FINAL BATCH: Complete remaining 398 products
-- WATER & SOIL PROBIOTICS (66), SOIL TREATMENT (17),
-- WATER PROBIOTICS (44), GUT PROBIOTICS (55), OTHERS (216)
-- Total: All 814 products fully imported
-- =============================================================

INSERT INTO public.product_master
  (brand, product_name, category, sub_category, form, unit_type, package_size, base_unit)
VALUES
  -- WATER & SOIL PROBIOTICS (66)
  ('ForU International', '8 PH', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('ForU International', '8PH', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Amazing Biotech Pvt Ltd', 'AB Pro', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Alta', 'Altasoil', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Amnion Bio Sciences', 'AM Care', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Amazing Biotech Pvt Ltd', 'AMAZ PRO', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Sukhraj&Company', 'Aqua Clean', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Sukhraj&Company', 'Aqua Clean', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Aqua Seed Enterprise', 'AQUA GUARD PRO', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Sheng Long', 'Aquachip', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Aries Agro (STB Marketing Pvt Ltd)', 'Aquazin plus', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Sanjeev Agro-vet private limited', 'Avant pro ps', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Poseidon Biotech', 'B4', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('De Generic Bio - Tech Private Limited', 'Bio-Supreme (1+1 offer)', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('SURYA BIOAAA', 'BIOA-PS', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('SURYA BIOAAA', 'BIOA-SOWAPRO', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biosmart Formulations', 'Biocare 3 In 1', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Neospark', 'Bioclear', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Gentle Bio-Sciences', 'Biofloc', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('CONIAN BIO SCIENCES', 'Coni Feed Pro', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Dr Pharma', 'D-Soft', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Dr Pharma', 'D-Soft', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Lifecare probiotics', 'Eco care 50', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 100, 'g'),
  ('Virbac', 'Eco Marine', 'WATER & SOIL PROBIOTICS', NULL, 'tablet', 'tab', 80, 'tab'),
  ('Lifecare probiotics', 'Eco-care', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 100, 'g'),
  ('Biostadt India Limited', 'Eco-Pro', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Biostadt India Limited', 'Environ Ac Power', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Biostadt India Limited', 'Environ-AC', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Reddy Drugs (KGR Marketing)', 'Geo-Prob', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Helia', 'Helia Uni-pro', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 250, 'g'),
  ('Biosmart Formulations', 'Hunter WF', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 3000, 'g'),
  ('Matrix sea Foods India Limited', 'Legend', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Maple Orgtech India Pvt Ltd', 'Maple EM.1 - Aquamagic', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Sujay Biotech', 'Micro Power Fish', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Sujay Biotech', 'Micro Power Prawn', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Intas Pharmaceutical Ltd', 'MilPond Terra', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Gentle Bio-Sciences', 'P4 Soil', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Bayer Pharmaceuticals Pvt Ltd', 'PondDtox', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Vinnbio', 'Pondpro', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('SRI Vasista Biotech', 'POWER PS', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('SRI Vasista Biotech', 'POWER PS', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Proprenz Biotech Pvt Ltd', 'Pro - Life', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 10000, 'g'),
  ('SRI Vasista Biotech', 'PRO -LIVE', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('ABT', 'Pro B Activa', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Rallis India Limited', 'Pro B Aqua', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Virbac', 'PRO MARINE', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('De Generic Bio - Tech Private Limited', 'Pro-Bact', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Vinmax Aqua Solutions', 'PROBIVIN-WS', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 2000, 'g'),
  ('Biofactor', 'Procare-W', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Biostadt India Limited', 'Profs', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('SRI Vasista Biotech', 'ProGain', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Synergy Biotech', 'ProSap', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Nthrys', 'Rhodopure', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Hallmark', 'Rizer', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Sandhya Feeds', 'San pro ps', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Sandhya Feeds', 'San Pro WS', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('CP Prime', 'Super Bottom', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('CP India Pvt Ltd', 'Super PS', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Poseidon Biotech', 'SUPREM PS', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Neospark', 'TerraGard - SP', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Microbasia', 'Thionil-SP', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Hallmark', 'Trubac', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Sanzyme LTD', 'Uni - Pond', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Sanzyme LTD', 'Uni Clear', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Natural Life Sciences', 'V-Shield', 'WATER & SOIL PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Vinmax Aqua Solutions', 'Vinpro PS', 'WATER & SOIL PROBIOTICS', NULL, 'liquid', 'ltr', 25000, 'ml'),

  -- SOIL TREATMENT (17)
  ('CP India Pvt Ltd', 'A soil', 'SOIL TREATMENT', NULL, 'powder', 'kg', 20000, 'g'),
  ('ForU International', 'B Green', 'SOIL TREATMENT', NULL, 'powder', 'gm', 500, 'g'),
  ('ForU International', 'B Green', 'SOIL TREATMENT', NULL, 'powder', 'kg', 1000, 'g'),
  ('Bio Aqua Life', 'Bio-soil', 'SOIL TREATMENT', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biomass Innovations', 'Ecdises', 'SOIL TREATMENT', NULL, 'powder', 'kg', 3000, 'g'),
  ('De Generic Bio - Tech Private Limited', 'Generic PS', 'SOIL TREATMENT', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('De Generic Bio - Tech Private Limited', 'Generic PS', 'SOIL TREATMENT', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Poseidon Biotech', 'HERBOSOL', 'SOIL TREATMENT', NULL, 'liquid', 'ml', 50, 'ml'),
  ('Neospark', 'HydroFloc', 'SOIL TREATMENT', NULL, 'powder', 'kg', 5000, 'g'),
  ('Neospark', 'Hydrofloc', 'SOIL TREATMENT', NULL, 'powder', 'kg', 10000, 'g'),
  ('KINGSTON MARINE INC', 'Jumper', 'SOIL TREATMENT', NULL, 'powder', 'gm', 500, 'g'),
  ('Neospark', 'SludgNil', 'SOIL TREATMENT', NULL, 'powder', 'kg', 1000, 'g'),
  ('Amnion Bio Sciences', 'Soil Fresh', 'SOIL TREATMENT', NULL, 'powder', 'kg', 1000, 'g'),
  ('Vinmax Aqua Solutions', 'Soil Guard', 'SOIL TREATMENT', NULL, 'powder', 'kg', 1000, 'g'),
  ('Hallmark', 'Ultima', 'SOIL TREATMENT', NULL, 'powder', 'kg', 1000, 'g'),
  ('ForU International', 'Weed Out', 'SOIL TREATMENT', NULL, 'powder', 'kg', 5000, 'g'),
  ('SKYRIDGE', 'Zemoca', 'SOIL TREATMENT', NULL, 'powder', 'kg', 1000, 'g'),

  -- WATER PROBIOTICS (44)
  ('Alta', 'Altapro', 'WATER PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Amnion Bio Sciences', 'AM PRO pond', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Amazing Biotech Pvt Ltd', 'AMAZ DE-NIT', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Amazing Biotech Pvt Ltd', 'AMAZ RED PH', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('SKYRIDGE', 'Aqvavin', 'WATER PROBIOTICS', NULL, 'powder', 'gm', 250, 'g'),
  ('SKYRIDGE', 'Aqvavin', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Srinivasa Cystine', 'Avant D- Flow', 'WATER PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Srinivasa Cystine', 'Avant pro w', 'WATER PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Kemin', 'BactoGEST', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Virbac', 'BIO MARINE', 'WATER PROBIOTICS', NULL, 'liquid', 'ltr', 4000, 'ml'),
  ('Gentle Bio-Sciences', 'Biofloc SP', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Neospark', 'BioRemid-Aqua', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('ABT', 'Chelcop Gel', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biofactor', 'Cyst Arrest (Microcystis)', 'WATER PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Aqua Seed Enterprise', 'DURONTO BRIDDHI PLUS', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Microl Remedies', 'Ecotech', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biofactor', 'Hydro Prow', 'WATER PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Rand Aqua', 'Indus', 'WATER PROBIOTICS', NULL, 'powder', 'gm', 40, 'g'),
  ('Rand Aqua', 'Manna', 'WATER PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Leo Aqua Laboratories', 'Microbial - Tab', 'WATER PROBIOTICS', NULL, 'powder', 'gm', 250, 'g'),
  ('Intas Pharmaceutical Ltd', 'Milpond Hydro', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Intas+ Biostadt+ Microbasia', 'MilpondHydro+ Wockcee+ Thionil-SP', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biofactor', 'Modiphy', 'WATER PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Til Bio sciences', 'Novib', 'WATER PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Sheng Long', 'NutriPro', 'WATER PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('CapriEnzymes', 'O-CONTROL', 'WATER PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('CapriEnzymes', 'P-SPARK', 'WATER PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Pellucid Lifesciences Pvt.Ltd', 'Pellupro Aqua', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Pellucid Lifesciences Pvt.Ltd', 'Pellupro Max', 'WATER PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('CP India Pvt Ltd', 'Ph Fixer Plus', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('SKYRIDGE', 'Phishkey', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('De Generic Bio - Tech Private Limited', 'PlanktAll-(1+1)', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biosmart Formulations', 'Pond Fresh', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Bayer Pharmaceuticals Pvt Ltd', 'Pondplus', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Synergy Biotech', 'Pro Bac BC', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Zymonutrients Pvt Ltd', 'PROBIOPOND', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biofactor', 'Regalis', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('INVE Aquaculture', 'Sanolife Pro W', 'WATER PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Virbac', 'Sokrena-WS', 'WATER PROBIOTICS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('CP India Pvt Ltd', 'Super Biotic', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Sanzyme LTD', 'Uni Ecosense', 'WATER PROBIOTICS', NULL, 'powder', 'gm', 250, 'g'),
  ('Sanzyme LTD', 'Uni-Ecosense', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Vinmax Aqua Solutions', 'VinAlgae', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 5000, 'g'),
  ('KINGSTON MARINE INC', 'Vipro', 'WATER PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),

  -- GUT PROBIOTICS (55)
  ('Sheng Long', 'Allicin', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Matrix sea Foods India Limited', 'Allways', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Amnion Bio Sciences', 'AM Garcin', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Amnion Bio Sciences', 'AM PROGUT', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Nuclein Life Sciences', 'Anti White Gut', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Biostadt India Limited', 'AquaLact', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Srinivasa Cystine', 'Avant Bact', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Blue bell', 'Bell Lact', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biomed Techno Ventures', 'Bio Care VW', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('SURYA BIOAAA', 'BIOA-GUTVIT', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Lifecare probiotics', 'Care protect', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('KINGSTON MARINE INC', 'Citra', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Aqua Seed Enterprise', 'CLEAN & CLEAR (LIQUID)', 'GUT PROBIOTICS', NULL, 'liquid', 'ml', 500, 'ml'),
  ('Confier International Pvt Ltd', 'Confier Feed Bite', 'GUT PROBIOTICS', NULL, 'liquid', 'ltr', 2000, 'ml'),
  ('Hallmark', 'Crypton', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('KINGSTON MARINE INC', 'D-White', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('De Generic Bio - Tech Private Limited', 'De-Gut', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 250, 'g'),
  ('Til Bio sciences', 'Eco Clean', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 250, 'g'),
  ('Matrix sea Foods India Limited', 'Enzolac', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('CP India Pvt Ltd', 'Erawan - G', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Gentle Bio-Sciences', 'FeedEX', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('CapriEnzymes', 'G-PROTECT', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Blue bell', 'Go White', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Lifecare probiotics', 'Gut care', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('J.S. Pharma Chem', 'Gut cure', 'GUT PROBIOTICS', NULL, 'liquid', 'ml', 100, 'ml'),
  ('Vinmax Aqua Solutions', 'Gut Cure', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Proprenz Biotech Pvt Ltd', 'Gut-Life', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Bio Genetics', 'Gut-PH', 'GUT PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Trusto Biotech', 'Gutgel', 'GUT PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Zymonutrients Pvt Ltd', 'GUTGUARD', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('SKYRIDGE', 'Gutvin', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Microl Remedies', 'Hepato Heal', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Biomass Innovations', 'Hepatopak', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Sheng Long', 'La Cure', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('SRI Vasista Biotech', 'Lacto Q', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biosmart Formulations', 'Lancer-6DX', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('KCP Sugars', 'Liver Tone', 'GUT PROBIOTICS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Intas Pharmaceutical Ltd', 'MilPond Vital', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Intas Pharmaceutical Ltd', 'MilPond Vital Plus', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 250, 'g'),
  ('Trusto Biotech', 'Moulting gel', 'GUT PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Karyotica', 'OLIGOMAX', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 7500, 'g'),
  ('Rand Aqua', 'Panacea', 'GUT PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Pellucid Lifesciences Pvt.Ltd', 'Pellupro Extra', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Rand Aqua', 'Protect', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Reddy Drugs(KGR Marketing)', 'Revive', 'GUT PROBIOTICS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Reddy Drugs(KGR Marketing)', 'Revive', 'GUT PROBIOTICS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('INVE Aquaculture', 'Sanolife Pro 2', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('SB Biotech', 'SB GUT PRO-B', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Elim Chem Private Limited', 'Sporezyme', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('Biofactor', 'True Care', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('CP India Pvt Ltd', 'Varna', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),
  ('CONIAN BIO SCIENCES', 'Vircon', 'GUT PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Microbasia', 'White Label', 'GUT PROBIOTICS', NULL, 'powder', 'kg', 1000, 'g'),
  ('PVS Laboratories', 'White Master', 'GUT PROBIOTICS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('CP India Pvt Ltd', 'Zymetin', 'GUT PROBIOTICS', NULL, 'powder', 'gm', 500, 'g'),

  -- OTHERS (216 products - Part 1)
  ('Skyecpharma', 'Vim Boost', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('CREATIVE GREEN INNOVATION', 'Vir Resist', 'OTHERS', NULL, 'powder', 'kg', 15000, 'g'),
  ('Proprenz Biotech Pvt Ltd', 'Vira-Life', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Bio Aqua Life', 'Vita p gel', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Reddy Drugs(KGR Marketing)', 'Vitazyme C', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Zion Aquatech', 'Z-Cal min', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'ZINC PLUS', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'Zinc-Plus', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('CP India Pvt Ltd', 'Ultra lite', 'OTHERS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Sanzyme LTD', 'Uni Phyto plus', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Biofactor', 'V-Vacc', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Proprenz Biotech Pvt Ltd', 'Vibrio-Life', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Reddy Drugs(KGR Marketing)', 'Vibriocide', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Skyecpharma', 'Vim Boost', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Innovatives', 'SWATCH WHITE GM', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Tata Sodium Bicarbonate', 'Tata Soda', 'OTHERS', NULL, 'powder', 'kg', 50000, 'g'),
  ('Grobest Feeds', 'Tea seed Powder', 'OTHERS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Neospark', 'TekBlok', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Triveni In - Organics PVT LTD', 'TRIPAC MB', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Amnion Bio Sciences', 'Ultimin', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Blue Aqua', 'Soil Grow', 'OTHERS', NULL, 'powder', 'gm', 250, 'g'),
  ('Sun shine Laboratories', 'Ss mg', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'STRONG-PS', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Hallmark', 'Super Hit', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Hallmark', 'Super Vit M', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'SUPERNEX-Y', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('SKYRIDGE', 'SEKAPRO', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Skyecpharma', 'SkyMilk Plus', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Skyecpharma', 'SkyMilk Plus', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Proprenz Biotech Pvt Ltd', 'Sludge-Life', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Finar', 'Sodium Bicarbonate', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Finar', 'Sodium Perborate Tetrahydrate', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Rand Aqua', 'RePulse', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Reddy Drugs(KGR Marketing)', 'Respirator', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('CP India Pvt Ltd', 'RN2', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Reddy Drugs(KGR Marketing)', 'Sano Clean', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'SEA GUARD', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'SEA GUARD', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('SKYRIDGE', 'PROVIDRINK', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Rand Aqua', 'Prudence', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Neospark', 'QBac', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Reddy Drugs(KGR Marketing)', 'Quick yeast', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Reddy Drugs(KGR Marketing)', 'RDL Snail', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Prime Biologicas', 'Remedy', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('MARINE SOLUTIONS', 'Pro G', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('AMCON AQUACULTURE', 'PRO TRACT', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('KCP Sugars', 'Procyte', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('GENESIS VET PHARMA', 'Proteus', 'OTHERS', NULL, 'powder', 'kg', 3000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'PROTOGEL', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'PROTOGEL', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Commercial Grade', 'Potassium Permanganate Commercial', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Commercial Grade', 'PP', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Hallmark', 'Praw Pro', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'PREVENT-V', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'PREVENT-V', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Dakh Biotech', 'Prime Shrimp', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('SURYA BIOAAA', 'Pond King Master', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Commercial Grade', 'Potash', 'OTHERS', NULL, 'powder', 'kg', 50000, 'g'),
  ('Lab Grade', 'Potassium Chloride', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Vinmax Aqua Solutions', 'Potassium Chloride', 'OTHERS', NULL, 'powder', 'kg', 50000, 'g'),
  ('Finar', 'Potassium Permanganate', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Pellucid Lifesciences Pvt.Ltd', 'Pelluzite', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Pellucid Lifesciences Pvt.Ltd', 'Pelluzite-Y', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Gentle Bio-Sciences', 'Perma Potash [PP]', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Matrix sea Foods India Limited', 'Pioneer', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Proprenz Biotech Pvt Ltd', 'Plankt-Life', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Matrix sea Foods India Limited', 'POC FORTE SUPER', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Kemin', 'Pathoral', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Neospark', 'PearlSpar Dolmite', 'OTHERS', NULL, 'powder', 'kg', 40000, 'g'),
  ('Pellucid Lifesciences Pvt.Ltd', 'Pell-PS', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Pellucid Lifesciences Pvt.Ltd', 'Pellu-Sludge', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Pellucid Lifesciences Pvt.Ltd', 'Pellumin', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Pellucid Lifesciences Pvt.Ltd', 'Pellumin-Plus', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Sukhraj&Company', 'Oswa Soft', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Reddy Drugs(KGR Marketing)', 'OXY MASK', 'OTHERS', NULL, 'powder', 'kg', 2000, 'g'),
  ('Reddy Drugs(KGR Marketing)', 'OXYMASK', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Amnion Bio Sciences', 'OXYPLUSGRAN', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Amnion Bio Sciences', 'OXYPLUSGRAN', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('CapriEnzymes', 'P-RELEASE', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biofactor', 'Nutribase', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'O2FRESH', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Omics Bio sciences', 'Omiprovib', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Amnion Bio Sciences', 'Ostolact', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Amnion Bio Sciences', 'OSTOLACT', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Amnion Bio Sciences', 'OSTOLACT', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'NATROLITE', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'NIMBUZ', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'NIMBUZ', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'NIMBUZ', 'OTHERS', NULL, 'liquid', 'ltr', 10000, 'ml'),
  ('Reddy Drugs(KGR Marketing)', 'Nitro clear', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Proprenz Biotech Pvt Ltd', 'Nitro-Life', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Hallmark', 'Micron', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Proprenz Biotech Pvt Ltd', 'Min-Life', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Blue Aqua', 'Mini Grow', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'MOLTONEX', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'NAGADAX', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'NATROGRANULES', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Proprenz Biotech Pvt Ltd', 'Life-Line', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Commercial Grade', 'Limestone', 'OTHERS', NULL, 'powder', 'kg', 40000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'LIVONEL-GEL', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('SKYRIDGE', 'Louserid', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Commercial Grade', 'Magnesium Chloride', 'OTHERS', NULL, 'powder', 'kg', 50000, 'g'),
  ('Lab Grade', 'Magnesium Chloride', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Vinmax Aqua Solutions', 'Magnesium Chloride', 'OTHERS', NULL, 'powder', 'kg', 50000, 'g'),
  ('Mayur Magnesia Works', 'Magnesium Chloride - commercial grade', 'OTHERS', NULL, 'powder', 'kg', 50000, 'g'),
  ('Matrix sea Foods India Limited', 'Matrimim', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Blue Aqua', 'Maya', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Matrix sea Foods India Limited', 'MEGA OXY PRIME', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Neospark', 'MGS', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Amnion Bio Sciences', 'IODOTREAT', 'OTHERS', NULL, 'liquid', 'ml', 500, 'ml'),
  ('Biofactor', 'Kipper', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Sheng Long', 'La CaO', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Poseidon Biotech', 'LACTACT', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('LEO BIO-LOGICALS', 'LEAD', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'I-MACT', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Blue Aqua', 'Immuno Gro', 'OTHERS', NULL, 'liquid', 'ltr', 15000, 'ml'),
  ('Reddy Drugs(KGR Marketing)', 'Immunostim', 'OTHERS', NULL, 'liquid', 'ltr', 50000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'IODONEX-2%', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'IODONEX-20%', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Amnion Bio Sciences', 'HUMAGICGOLD (Granules)', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Metro Aqua Labs', 'HUNTER-V', 'OTHERS', NULL, 'powder', 'kg', 2500, 'g'),
  ('Commercial Grade', 'Hydrogen Peroxide', 'OTHERS', NULL, 'liquid', 'ltr', 30000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'HYGENEX', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Devee Biologicals Pvt Ltd', 'I Bac', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Devee Biologicals Pvt Ltd', 'I Min', 'OTHERS', NULL, 'powder', 'kg', 15000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'GROWWNEX', 'OTHERS', NULL, 'powder', 'kg', 20000, 'g'),
  ('SKYRIDGE', 'Gutscour', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Skyepharma', 'Heeppro', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'HEPATOXIN-B', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Biofactor', 'High-K(Aqua)', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Hallmark', 'Hit', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Proprenz Biotech Pvt Ltd', 'Gill-Life', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Neospark', 'Glycosan', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('AMCON AQUACULTURE', 'Grogen', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'GROVIT-GEL', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'GROW CALL', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'GROW CALL', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Reddy Drugs(KGR Marketing)', 'Floc-6', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Reddy Drugs(KGR Marketing)', 'Flow Min', 'OTHERS', NULL, 'liquid', 'ltr', 15000, 'ml'),
  ('Biomass Innovations', 'Garrisons', 'OTHERS', NULL, 'powder', 'kg', 3000, 'g'),
  ('Neospark', 'Gasorid', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biofactor', 'Gelfact', 'OTHERS', NULL, 'liquid', 'ltr', 25000, 'ml'),
  ('Reddy Drugs(KGR Marketing)', 'Geomin', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Finar', 'Ferric chloride', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Vinmax Aqua Solutions', 'Ferric Chloride', 'OTHERS', NULL, 'powder', 'kg', 60000, 'g'),
  ('Commercial Grade', 'Ferric-Chloride', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Skyepharma', 'FertMilk', 'OTHERS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Commercial Grade', 'Fish feed Pindi', 'OTHERS', NULL, 'powder', 'kg', 60000, 'g'),
  ('Reddy Drugs(KGR Marketing)', 'Floc-6', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('AMCON AQUACULTURE', 'Earlymin 10 Kg', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Til Bio sciences', 'ECOMMONIL', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Til Bio sciences', 'ECOTOXNIL', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Til Bio sciences', 'ECOTRAX', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Matrix sea Foods India Limited', 'Ensure', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Neospark', 'Ferbac Plus', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('SKYRIDGE', 'Decalmin', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Poseidon Biotech', 'DONTOX', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('AMCON AQUACULTURE', 'Double C-500G', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Hallmark', 'Dyna', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Hallmark', 'Dyna', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Biofactor', 'E-VACC(EHP)', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Biofactor', 'Dawn', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Dakh Biotech', 'DB-Dhanva', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Dakh Biotech', 'DB-Immuno', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Dakh Biotech', 'DB-VWINN-F', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('J.S. Pharma Chem', 'DCP', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Hallmark', 'DCP', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Bio Aqua Life', 'Chlore-D', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Confier International Pvt Ltd', 'Confier soil AFM', 'OTHERS', NULL, 'liquid', 'ltr', 2000, 'ml'),
  ('CONIAN BIO SCIENCES', 'Coni Live Care', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('KINGSTON MARINE INC', 'Croma', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('REVOLGENE', 'Culture Care', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Finar', 'Cupric Sulphate', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Vinmax Aqua Solutions', 'Calcium Chloride', 'OTHERS', NULL, 'powder', 'kg', 50000, 'g'),
  ('Commercial Grade', 'Calcium Chloride', 'OTHERS', NULL, 'powder', 'kg', 50000, 'g'),
  ('Lab Grade', 'Calcium Chloride', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Virbac', 'Calgo Phos', 'OTHERS', NULL, 'liquid', 'ltr', 4000, 'ml'),
  ('Virbac', 'Calgo Phos', 'OTHERS', NULL, 'liquid', 'ltr', 10000, 'ml'),
  ('Gentle Bio-Sciences', 'Ceevit', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Rayalaseema Bleaching', 'Bleaching Hi-Power', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Commercial Grade', 'Bleaching Powder 65', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('SKYRIDGE', 'Blue Green', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'BRONEX', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'BRONEX', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'C-PLUS', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Bio Genetics', 'Bio Zinc', 'OTHERS', NULL, 'powder', 'kg', 2000, 'g'),
  ('SURYA BIOAAA', 'BIOA - NITRICURE', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('KCP Sugars', 'Bion', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'BIONEX', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'BIONEX', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Rayalaseema Bleaching', 'Bleaching', 'OTHERS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Provet', 'Bacitox', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('AMCON AQUACULTURE', 'Bactofen 500g', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Skyepharma', 'Belex-C', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Skyepharma', 'BELEX-C', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Matrix sea Foods India Limited', 'BINDEX ZEL', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Proprenz Biotech Pvt Ltd', 'Bio - Life (1+1 offer)', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Amnion Bio Sciences', 'AM CALPLUS', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Amnion Bio Sciences', 'AM SNIPER', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Sanjeev Agro-vet private limited', 'Avant D Snail', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Srinivasa Cystine', 'Avant Life', 'OTHERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Bio Aqua Life', 'B-Calcium Peroxide', 'OTHERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Bio Aqua Life', 'B-Vitagel', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Matrix sea Foods India Limited', 'ADVEX-PS', 'OTHERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Matrix sea Foods India Limited', 'AIM', 'OTHERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Reddy Drugs(KGR Marketing)', 'AlkaForte', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('CP India Pvt Ltd', 'Alpha Pro Advance', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Amnion Bio Sciences', 'AM CALPLUS', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Amnion Bio Sciences', 'AM CALPLUS', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'GROWWNEX NEW', 'OTHERS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'LIVONEL-GEL', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'MINRICH', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Nexell Laboratories pvt. ltd', 'MOLTONEX', 'OTHERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Nexell Laboratories pvt. ltd', 'OXI FRESS', 'OTHERS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Poseidon Biotech', 'Acridon', 'OTHERS', NULL, 'liquid', 'ltr', 5000, 'ml')
ON CONFLICT DO NOTHING;