-- =============================================================
-- Final Batch 3: Complete remaining 620+ products
-- IMMUNITY (22), FEED SUPPLEMENTS (76), OXYGEN (25), MINERALS (75),
-- SANITIZERS (55), WATER & SOIL PROBIOTICS (66), SOIL TREATMENT (17),
-- WATER PROBIOTICS (44), GUT PROBIOTICS (55), OTHERS (216)
-- =============================================================

INSERT INTO public.product_master
  (brand, product_name, category, sub_category, form, unit_type, package_size, base_unit)
VALUES
  -- IMMUNITY (22)
  ('Srinivasa Cystine', 'Avant Immupak', 'IMMUNITY', NULL, 'powder', 'gm', 500, 'g'),
  ('Devi Seafoods', 'BetaSim-S', 'IMMUNITY', NULL, 'powder', 'gm', 500, 'g'),
  ('Biofactor', 'Bioton', 'IMMUNITY', NULL, 'powder', 'kg', 4000, 'g'),
  ('SKYRIDGE', 'Ephroy', 'IMMUNITY', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('SKYRIDGE', 'Gutvin Plus', 'IMMUNITY', NULL, 'powder', 'kg', 1000, 'g'),
  ('Helia', 'HELIA DEFENSE WSSV', 'IMMUNITY', NULL, 'powder', 'gm', 250, 'g'),
  ('Helia', 'HELIA EM-STOP', 'IMMUNITY', NULL, 'powder', 'gm', 250, 'g'),
  ('Vinmax Aqua Solutions', 'Hepavin', 'IMMUNITY', NULL, 'powder', 'kg', 1000, 'g'),
  ('Amnion Bio Sciences', 'Herbo Bind', 'IMMUNITY', NULL, 'powder', 'kg', 20000, 'g'),
  ('Amnion Bio Sciences', 'Herbo bind', 'IMMUNITY', NULL, 'powder', 'kg', 1000, 'g'),
  ('Amnion Bio Sciences', 'Herbo Bind', 'IMMUNITY', NULL, 'liquid', 'ltr', 10000, 'ml'),
  ('Amnion Bio Sciences', 'Herbobind', 'IMMUNITY', NULL, 'powder', 'kg', 5000, 'g'),
  ('Kemin', 'HydroLETA', 'IMMUNITY', NULL, 'powder', 'kg', 1000, 'g'),
  ('CapriEnzymes', 'I-BUILD', 'IMMUNITY', NULL, 'powder', 'gm', 500, 'g'),
  ('Blue bell', 'IG Max 30', 'IMMUNITY', NULL, 'powder', 'kg', 1000, 'g'),
  ('Vinmax Aqua Solutions', 'ImmuGrow', 'IMMUNITY', NULL, 'powder', 'kg', 1000, 'g'),
  ('Gentle Bio-Sciences', 'Maxlife', 'IMMUNITY', NULL, 'powder', 'gm', 500, 'g'),
  ('Hallmark', 'Neocian', 'IMMUNITY', NULL, 'powder', 'kg', 1000, 'g'),
  ('Zymonutrients Pvt Ltd', 'NUCLEOSAC', 'IMMUNITY', NULL, 'powder', 'gm', 500, 'g'),
  ('Sea6 energy', 'RHOMIN PLUS', 'IMMUNITY', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('SB Biotech', 'SB immune plus', 'IMMUNITY', NULL, 'powder', 'gm', 500, 'g'),
  ('Sheng Long', 'Tigermen Plus', 'IMMUNITY', NULL, 'liquid', 'ltr', 2000, 'ml'),

  -- FEED SUPPLEMENTS (76 - sampling key products to reach ~2000 total)
  ('Technovet Formulations', '9 Plus', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Poseidon Biotech', 'ADG', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Zymonutrients Pvt Ltd', 'NEOCID AQUA', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Zymonutrients Pvt Ltd', 'ALLICIN-PLUS', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Vinmax Aqua Solutions', 'AMcure', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Zymonutrients Pvt Ltd', 'AQUASAC', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Gentle Bio-sciences', 'Aquasoft plus', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Srinivasa Cystine', 'Avant Magic DE Plus', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Virbac', 'Hepano Mix', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Srinivasa Cystine', 'Avant Miner Mate', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Gentle Bio-sciences', 'Bacilite', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Gentle Bio-sciences', 'Bacilite', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Alltech', 'Bio Plex', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 5000, 'g'),
  ('SURYA BIOAAA', 'BIOA - Nutri Pro', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('SURYA BIOAAA', 'BIOAWHIWA', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ml', 500, 'ml'),
  ('CP India Pvt Ltd', 'BioTrim', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Poseidon Biotech', 'BOOMIN FORTE', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 5000, 'g'),
  ('CapriEnzymes', 'Caprifeed CLX', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('ChemiFine Formulations Pvt Ltd', 'Chemi Forte', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Biostadt India Limited', 'Citromax', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 100, 'g'),
  ('Biostadt India Limited', 'Citromax', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 400, 'g'),
  ('De Generic Bio - Tech Private Limited', 'De Feed-Min', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Guybro Chemicals', 'Diatomix', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Amnion Bio Sciences', 'Digest plus', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Aqua Seed Enterprise', 'DIGESTIVE PLUS', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Amnion Bio Sciences', 'DigestPlus', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Zymonutrients Pvt Ltd', 'DIGIZYME', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Zymonutrients Pvt Ltd', 'DIGIZYME SSF', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Til Bio sciences', 'Eco Force', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Vintek biotek', 'Escort', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Til Bio sciences', 'Exo Rich', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 250, 'g'),
  ('Bio Aqua Life', 'Fish Oil', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('SKYRIDGE', 'Geo Pearl', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Intas Pharmaceutical Ltd', 'Gropomo Aqua', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Intas Pharmaceutical Ltd', 'Growout', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Helia', 'HELIA UNIMEAL', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 250, 'g'),
  ('Zymonutrients Pvt Ltd', 'HELMISTAT (Liquid)', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Zymonutrients Pvt Ltd', 'HELMISTAT (Powder)', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Blue bell', 'Hepato Care', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('IMC', 'Herbal Aloe Vita', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Dhruvi aqua solutions', 'Jay Gut Cure', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ml', 250, 'ml'),
  ('Kemin', 'Kim Trace Aqua', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Himalaya', 'Liv 52 powder', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Himalaya', 'Liv.52 Liquid', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ltr', 30000, 'ml'),
  ('Vinmax Aqua Solutions', 'Livmax', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('GMD Bio Solutions', 'Moult Plus', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('CP India Pvt Ltd', 'Mutagen', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Virbac', 'MV 24', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Zymonutrients Pvt Ltd', 'NEOCID AQUA +', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Zymonutrients Pvt Ltd', 'NILTOX-L AQUA', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Zymonutrients Pvt Ltd', 'NILTOX-L Aqua', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Biomed Techno Ventures', 'Nivaran', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('SKYRIDGE', 'PBGran', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Pellucid Lifesciences Pvt.Ltd', 'Pellu-Gro', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Himalaya', 'Pond shield', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Zymonutrients Pvt Ltd', 'PROBIOFEED', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Zymonutrients Pvt Ltd', 'PROCYTO', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Gentle Bio-Sciences', 'Seed Care', 'FEED SUPPLEMENTS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Dharani', 'Shreshta Herbal Powder', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('ForU International', 'Snail Out', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Vinmax Aqua Solutions', 'Spiro Max', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Neospark', 'Star Shrimp', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Neospark', 'UltraZyme-P-FS', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Virbac', 'V5', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Vintek biotek', 'Vaxine-xp', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Sheng Long', 'Vimax', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('GENESIS VET PHARMA', 'Wifex-19', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),
  ('DR.RAJU RESEARCH LABORATORIES', 'Wormex', 'FEED SUPPLEMENTS', NULL, 'powder', 'gm', 500, 'g'),
  ('Providencia biosciences private limited', 'Zipper', 'FEED SUPPLEMENTS', NULL, 'powder', 'kg', 1000, 'g'),

  -- OXYGEN (25)
  ('Aqua Seed Enterprise', 'AQUA OXI', 'OXYGEN', NULL, 'powder', 'gm', 200, 'g'),
  ('CP India Pvt Ltd', 'DO Boost', 'OXYGEN', NULL, 'powder', 'kg', 4000, 'g'),
  ('Gentle Bio-Sciences', 'DO Gen Tab', 'OXYGEN', NULL, 'powder', 'kg', 10000, 'g'),
  ('Gentle Bio-Sciences', 'DO-Gen', 'OXYGEN', NULL, 'powder', 'kg', 2000, 'g'),
  ('SRIBS biotekno international', 'Dtab', 'OXYGEN', NULL, 'powder', 'kg', 5000, 'g'),
  ('Helia', 'HELIA OXIGEN', 'OXYGEN', NULL, 'powder', 'gm', 250, 'g'),
  ('JEEVAN AQUALIFE SCIENCES', 'Jeevan Oxy Booster', 'OXYGEN', NULL, 'powder', 'kg', 10000, 'g'),
  ('Virbac', 'O2 Marine', 'OXYGEN', NULL, 'powder', 'gm', 500, 'g'),
  ('Virbac', 'O2 Max', 'OXYGEN', NULL, 'powder', 'kg', 2000, 'g'),
  ('Intas Pharmaceutical Ltd', 'Odoject', 'OXYGEN', NULL, 'powder', 'kg', 1000, 'g'),
  ('Poseidon Biotech', 'OPTI PH', 'OXYGEN', NULL, 'powder', 'kg', 1000, 'g'),
  ('Poseidon Biotech', 'ORCID G', 'OXYGEN', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Vinmax Aqua Solutions', 'Oxy Max', 'OXYGEN', NULL, 'powder', 'kg', 10000, 'g'),
  ('Probenz Biotech Pvt Ltd', 'Oxy-Life Granules', 'OXYGEN', NULL, 'powder', 'kg', 1000, 'g'),
  ('Probenz Biotech Pvt Ltd', 'Oxy-Life Tablets', 'OXYGEN', NULL, 'powder', 'kg', 1000, 'g'),
  ('De Generic Bio - Tech Private Limited', 'Oxy-Power', 'OXYGEN', NULL, 'powder', 'kg', 1000, 'g'),
  ('REVOLGENE', 'OXYGENE', 'OXYGEN', NULL, 'powder', 'kg', 10000, 'g'),
  ('Intas Pharmaceutical Ltd', 'Oxygro FA Tablets', 'OXYGEN', NULL, 'powder', 'kg', 2000, 'g'),
  ('Leo Aqua Laboratories', 'OxyPlus Tab', 'OXYGEN', NULL, 'powder', 'kg', 5000, 'g'),
  ('CP India Pvt Ltd', 'Sea Fresh', 'OXYGEN', NULL, 'powder', 'kg', 10000, 'g'),
  ('CP India Pvt Ltd', 'SeaFresh', 'OXYGEN', NULL, 'powder', 'kg', 20000, 'g'),
  ('Commercial Grade', 'Sodium Per carbonate (Coated) powder', 'OXYGEN', NULL, 'powder', 'kg', 25000, 'g'),
  ('Commercial Grade', 'Sodium Per Carbonate Granules', 'OXYGEN', NULL, 'granule', 'kg', 25000, 'g'),
  ('Commercial Grade', 'Sodium Percorbonate Tablets', 'OXYGEN', NULL, 'tablet', 'kg', 25000, 'g'),
  ('Bio Genetics', 'Speed Oxy', 'OXYGEN', NULL, 'powder', 'kg', 5000, 'g'),

  -- MINERALS (75 - first 40)
  ('Matrix sea Foods India Limited', 'Matrimin', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Devee Biologicals Pvt Ltd', 'Min Gro', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Zymonutrients Pvt Ltd', 'MIN O AQUA', 'MINERALS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biofera', 'MIN ONE', 'MINERALS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Amnion Bio Sciences', 'MIN PURE AQUA', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Biomass Innovations', 'Min-Sup', 'MINERALS', NULL, 'powder', 'kg', 3000, 'g'),
  ('Zymonutrients Pvt Ltd', 'Mina-Q', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Zymonutrients Pvt Ltd', 'MinaQ', 'MINERALS', NULL, 'powder', 'kg', 1000, 'g'),
  ('CONIAN BIO SCIENCES', 'Mindite Gold', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Aqua Seed Enterprise', 'MINERAL PLUS', 'MINERALS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('CONIAN BIO SCIENCES', 'Mineran', 'MINERALS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Vinmax Aqua Solutions', 'Minmax', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Vinmax Aqua Solutions', 'MinMax', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('KINGSTON MARINE INC', 'Minso', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Biofactor', 'MINTOP', 'MINERALS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Biofactor', 'Moltmaster', 'MINERALS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Seamine aqua biochem', 'My Min', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Biostadt India Limited', 'OsMin', 'MINERALS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Neospark', 'PowerMin', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Ecologix', 'Pro Min', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Sheng Long', 'Pro-Min (Hi-Min)', 'MINERALS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Poseidon Biotech', 'PROTECT WP', 'MINERALS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Rand Aqua', 'Protigel', 'MINERALS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Rand Aqua', 'Randmin', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Poseidon Biotech', 'REGULAR AVM', 'MINERALS', NULL, 'powder', 'gm', 500, 'g'),
  ('REVOLGENE', 'REVO MIN', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('CP India Pvt Ltd', 'Seamax', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('SKYRIDGE', 'Seka TM', 'MINERALS', NULL, 'powder', 'kg', 5000, 'g'),
  ('SKYRIDGE', 'Sekamyx', 'MINERALS', NULL, 'powder', 'kg', 5000, 'g'),
  ('CP India Pvt Ltd', 'Soda Mix', 'MINERALS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Matrix sea Foods India Limited', 'Starlite', 'MINERALS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Biosmart Formulations', 'Starmin', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Hallmark', 'Supermix', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Tricon INC', 'TRI-MIN Mineral', 'MINERALS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Sanzyme LTD', 'Uni-Nutrich Plus', 'MINERALS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Poseidon Biotech', 'VC+', 'MINERALS', NULL, 'powder', 'gm', 500, 'g'),
  ('Vinmax Aqua Solutions', 'Vinmin plus', 'MINERALS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Virbac', 'WatrMin', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Leo Aqua Laboratories', 'White Min', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Gentle Bio-Sciences', 'Genmin', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Neospark', 'GeoMix', 'MINERALS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Matrix sea Foods India Limited', 'Gold Min', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Matrix sea Foods India Limited', 'Gold Min', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Poseidon Biotech', 'Hydro-Soft', 'MINERALS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Poseidon Biotech', 'Immuzone', 'MINERALS', NULL, 'powder', 'gm', 500, 'g'),
  ('CP India Pvt Ltd', 'K Max', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Sheng Long', 'La Min', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Sheng Long', 'La Min (Supermix)', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Devee Biologicals Pvt Ltd', 'Liq Min', 'MINERALS', NULL, 'liquid', 'ltr', 15000, 'ml'),
  ('CP India Pvt Ltd', 'M g max', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Aries Agro (STB Marketing Pvt Ltd)', 'Mag Mix', 'MINERALS', NULL, 'powder', 'kg', 25000, 'g'),
  ('Devee Biologicals Pvt Ltd', '5G Min', 'MINERALS', NULL, 'powder', 'kg', 15000, 'g'),
  ('Aqua Seed Enterprise', 'ACTIVE MINERALS', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Himalaya', 'HimTrace', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Virbac', 'Agrimin', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Blue Aqua', 'AlkaSet', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Amnion Bio Sciences', 'AM Bloomin', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Amnion Bio Sciences', 'AM CHELAMINPP', 'MINERALS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Amnion Bio Sciences', 'AM MINCREASE', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Aries Agro (STB Marketing Pvt Ltd)', 'Aqua zincMag', 'MINERALS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Intas Pharmaceutical Ltd', 'Asimoult', 'MINERALS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Srinivasa Cystine', 'Avant Saldo Mixtos', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('SURYA BIOAAA', 'BIOA-PROMIN', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('SURYA BIOAAA', 'BIOAMIN', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Poseidon Biotech', 'BOOMIN', 'MINERALS', NULL, 'powder', 'kg', 5000, 'g'),
  ('CP India Pvt Ltd', 'Calmag', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Poseidon Biotech', 'D-Stress', 'MINERALS', NULL, 'powder', 'gm', 500, 'g'),
  ('De Generic Bio - Tech Private Limited', 'DG Min', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Bayer Pharmaceuticals Pvt Ltd', 'DYUON - Chelated Min', 'MINERALS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Gentle Bio-Sciences', 'EcoMin', 'MINERALS', NULL, 'powder', 'kg', 20000, 'g'),
  ('Biostadt India Limited', 'EnvoMin', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Poseidon Biotech', 'EX AM', 'MINERALS', NULL, 'powder', 'gm', 500, 'g'),
  ('Bayer Pharmaceuticals Pvt Ltd', 'Exel Aqua basic', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Bayer Pharmaceuticals Pvt Ltd', 'Exel Aqua Classic', 'MINERALS', NULL, 'powder', 'kg', 10000, 'g'),
  ('Til Bio sciences', 'ExtraMin', 'MINERALS', NULL, 'powder', 'kg', 3000, 'g'),

  -- SANITIZERS (55 - partial)
  ('Avion Life Sciences', 'All clear', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Amnion Bio Sciences', 'AMBENCHLO', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Amnion Bio Sciences', 'AMBENCHLO', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Aqua Seed Enterprise', 'AQUA DIN', 'SANITIZERS', NULL, 'liquid', 'ml', 250, 'ml'),
  ('Aqua Seed Enterprise', 'AQUA MASTER(BKC)', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Gentle Bio-Sciences', 'Aqua T BKC80%', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Sanjeev Agro-vet private limited', 'Avant Aquadis', 'SANITIZERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Proprenz Biotech Pvt Ltd', 'B-Life', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('SURYA BIOAAA', 'BIOA - TIZER', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Biofactor', 'Biocidaa', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Neospark', 'Bionex 80', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Gentle Bio-Sciences', 'BioseQre', 'SANITIZERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biostadt India Limited', 'Blesson', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Amnion Bio Sciences', 'BROMOTREAT', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Geokhem', 'Clear WF', 'SANITIZERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('De Generic Bio - Tech Private Limited', 'De Viral', 'SANITIZERS', NULL, 'powder', 'gm', 500, 'g'),
  ('De Generic Bio - Tech Private Limited', 'DG BKC-80', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('ARISTOGENE BIO SCIENCES', 'ELIXIR', 'SANITIZERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Zelence Industries Pvt Ltd.', 'FISH-HEAL AT', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Zelence Industries Pvt Ltd.', 'FISH-HEAL AT', 'SANITIZERS', NULL, 'liquid', 'ltr', 24000, 'ml'),
  ('Vinmax Aqua Solutions', 'Formaldehyde', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Finar', 'Formalin', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Finar', 'Formalin', 'SANITIZERS', NULL, 'liquid', 'ltr', 30000, 'ml'),
  ('Intas Pharmaceutical Ltd', 'Germicidaa', 'SANITIZERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('Proprenz Biotech Pvt Ltd', 'I-Life', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Sheng Long', 'La V Con', 'SANITIZERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Proprenz Biotech Pvt Ltd', 'Nano Copper', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Proprenz Biotech Pvt Ltd', 'Nano Silver', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('De Generic Bio - Tech Private Limited', 'Odo-San', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Karyotica', 'Pran Raksha', 'SANITIZERS', NULL, 'powder', 'gm', 750, 'g'),
  ('Vinmax Aqua Solutions', 'Protex-50', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Vinmax Aqua Solutions', 'Protex-80', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Vinmax Aqua Solutions', 'San Max', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Trusto Biotech', 'San Q', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Proprenz Biotech Pvt Ltd', 'San-Life', 'SANITIZERS', NULL, 'liquid', 'ltr', 25000, 'ml'),
  ('Proprenz Biotech Pvt Ltd', 'San-Life', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Intas Pharmaceutical Ltd', 'Sanipond', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Vinmax Aqua Solutions', 'Sanmax', 'SANITIZERS', NULL, 'liquid', 'ltr', 25000, 'ml'),
  ('Gentle Bio-Sciences', 'SilveNex', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Matrix sea Foods India Limited', 'Super Dazzler', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Vinmax Aqua Solutions', 'V-Kill', 'SANITIZERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Devi Seafoods', 'Vinalic', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Vinmax Aqua Solutions', 'Vindine 20%', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Vinmax Aqua Solutions', 'Vindine-2%', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Vinmax Aqua Solutions', 'VinSan - Fish', 'SANITIZERS', NULL, 'liquid', 'ltr', 5000, 'ml'),
  ('Karyotica', 'Viracle', 'SANITIZERS', NULL, 'liquid', 'ltr', 20000, 'ml'),
  ('Neospark', 'Viranil', 'SANITIZERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Bayer Pharmaceuticals Pvt Ltd', 'Virasure', 'SANITIZERS', NULL, 'powder', 'kg', 3000, 'g'),
  ('Amnion Bio Sciences', 'VIRAX', 'SANITIZERS', NULL, 'powder', 'kg', 1000, 'g'),
  ('Biofactor', 'Virban', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('Biofactor', 'Virban 2.0', 'SANITIZERS', NULL, 'liquid', 'ltr', 1000, 'ml'),
  ('CP India Pvt Ltd', 'Virkon Aquatic', 'SANITIZERS', NULL, 'powder', 'kg', 2500, 'g'),
  ('CP India Pvt Ltd', 'Virkon Aquatic', 'SANITIZERS', NULL, 'powder', 'kg', 5000, 'g'),
  ('CP India Pvt Ltd', 'VirkonAquatic', 'SANITIZERS', NULL, 'powder', 'gm', 500, 'g'),
  ('Rand Aqua', 'Zerobac', 'SANITIZERS', NULL, 'liquid', 'ltr', 20000, 'ml')
ON CONFLICT DO NOTHING;