-- Fix pond creation after feed engine schema migration.
--
-- The client already generates feed_rounds through the Dart feed engine after
-- this RPC returns. Keep the database RPC focused on creating the pond only so
-- it cannot drift from the feed engine single source of truth.

DO $$
DECLARE
  v_signature TEXT;
BEGIN
  FOR v_signature IN
    SELECT pg_get_function_identity_arguments(p.oid)
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname = 'create_pond_with_feed_plan'
  LOOP
    EXECUTE format('DROP FUNCTION IF EXISTS public.create_pond_with_feed_plan(%s)', v_signature);
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_pond_with_feed_plan(
  p_farm_id UUID,
  p_name TEXT,
  p_area NUMERIC,
  p_stocking_date DATE,
  p_seed_count INTEGER,
  p_pl_size INTEGER,
  p_num_trays INTEGER,
  p_user_id UUID
) RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_pond_id UUID;
BEGIN
  IF auth.uid() IS NULL OR auth.uid() <> p_user_id THEN
    RAISE EXCEPTION 'Unauthorized pond creation request'
      USING ERRCODE = '42501';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.farms
    WHERE id = p_farm_id
      AND user_id = p_user_id
  ) THEN
    RAISE EXCEPTION 'Farm not found for current user'
      USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.ponds (
    farm_id,
    user_id,
    name,
    area,
    stocking_date,
    seed_count,
    pl_size,
    num_trays,
    status
  ) VALUES (
    p_farm_id,
    p_user_id,
    p_name,
    p_area,
    p_stocking_date,
    p_seed_count,
    p_pl_size,
    p_num_trays,
    'active'
  )
  RETURNING id INTO v_pond_id;

  RETURN v_pond_id::TEXT;
END;
$$;

COMMENT ON FUNCTION public.create_pond_with_feed_plan(
  UUID,
  TEXT,
  NUMERIC,
  DATE,
  INTEGER,
  INTEGER,
  INTEGER,
  UUID
) IS 'Creates a pond only. Feed rounds are generated by the Dart feed engine SSOT after RPC success.';
